FROM python:3.10.0-slim-buster
ENV APP_HOME =/app 
RUN MKDIR $APP_HOME
RUN MKDIR $APP_HOME/staticfiles
WORKDIR $APP_HOME

LABEL maintainer = 'muhammedseydali007@gmail.com'
LABEL description = 'This is my project'

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

RUN apt-get-update \
&& apt-get install -y build essentials \
&& apt-get install -y libpq-dev \ 
&& apt-get install -y gettext \
&& apt-get install -y netcat gec postgresql \
&& apt-get purge -y --auto-remove -o \
APT::AutoRemove::RecommendsImportant=False \
&& rm -rf /var/lib/apt/lists/


RUN pip3 install --upgradepip 
COPY ./requiremnts.txt /app/requirements.txt

RUN pip3 install -r requirements.txt\ 
COPY ./docker/local/django/entrypoint/entrypoint
RUN sed -i 's/\r $//g' / entrypoint
RUN chmod + x / entrypoint 

COPY ./docker/local/django/start/start 
RUN sed -i 's/\r $//g' /start 
RUN chmod +x start
ENTRYPOINT ["/entrypoint"]





