# Generated by Django 4.0.4 on 2022-05-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='milege',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='miles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='passengers',
            field=models.IntegerField(),
        ),
    ]
