# Generated by Django 4.0.4 on 2022-05-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_milege_alter_cars_miles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
