# Generated by Django 4.0.4 on 2022-05-13 10:25

import ckeditor.fields
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_fuel_type_alter_cars_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cruise control', 'cruise control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air conditioning', 'Air conditioning'), ('seat heating', 'seat heating'), ('Alarm system', 'Alarm system'), ('Park assistant', 'Park assistant'), ('Power steering', 'Power steering'), ('Reverse camera', 'Reverse camera'), ('Direct fuel injection', 'Direct fuel injection'), ('Auto start/stop', 'Auto start/stop'), ('wind deflector', 'wind deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=197),
        ),
    ]
